//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDK.Debug {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDK.Debug.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Debugger.
        /// </summary>
        internal static string ProgrammableBlockExtensions_Install_AttachDebugger {
            get {
                return ResourceManager.GetString("ProgrammableBlockExtensions_Install_AttachDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind DLL.
        /// </summary>
        internal static string ProgrammableBlockExtensions_Install_BindDLLButtonText {
            get {
                return ResourceManager.GetString("ProgrammableBlockExtensions_Install_BindDLLButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation denied because the edit button could not be found.
        /// </summary>
        internal static string ProgrammableBlockExtensions_Install_NoEditButton {
            get {
                return ResourceManager.GetString("ProgrammableBlockExtensions_Install_NoEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debug plugin is installed and ready..
        /// </summary>
        internal static string ProgrammableBlockExtensions_Install_Ready {
            get {
                return ResourceManager.GetString("ProgrammableBlockExtensions_Install_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbind DLL.
        /// </summary>
        internal static string ProgrammableBlockExtensions_Install_UnbindDLLButtonText {
            get {
                return ResourceManager.GetString("ProgrammableBlockExtensions_Install_UnbindDLLButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loaded assembly could not be recognized as a programmable block script container..
        /// </summary>
        internal static string ProgrammableBlockExtensions_LoadScriptAssembly_InvalidAssembly {
            get {
                return ResourceManager.GetString("ProgrammableBlockExtensions_LoadScriptAssembly_InvalidAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loaded assembly contains too many grid programs. Only one was expected..
        /// </summary>
        internal static string ProgrammableBlockExtensions_LoadScriptAssembly_TooManyGridPrograms {
            get {
                return ResourceManager.GetString("ProgrammableBlockExtensions_LoadScriptAssembly_TooManyGridPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin was unable to bind a programmable block. This is most likely caused by changes to the game..
        /// </summary>
        internal static string ProgrammableBlockExtensions_OnBindScriptDll_BindingError {
            get {
                return ResourceManager.GetString("ProgrammableBlockExtensions_OnBindScriptDll_BindingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding Failed.
        /// </summary>
        internal static string ProgrammableBlockExtensions_OnBindScriptDll_BindingFailed {
            get {
                return ResourceManager.GetString("ProgrammableBlockExtensions_OnBindScriptDll_BindingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind Script DLL.
        /// </summary>
        internal static string ProgrammableBlockExtensions_OnBindScriptDll_BindScriptDLL {
            get {
                return ResourceManager.GetString("ProgrammableBlockExtensions_OnBindScriptDll_BindScriptDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Programmable Block Debugging.
        /// </summary>
        internal static string ProgrammableBlockExtensions_OnBindScriptDll_EnableDebugging {
            get {
                return ResourceManager.GetString("ProgrammableBlockExtensions_OnBindScriptDll_EnableDebugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Assembly (*.dll,*.exe)|*.dll;*.exe.
        /// </summary>
        internal static string ProgrammableBlockExtensions_OnBindScriptDll_Filters {
            get {
                return ResourceManager.GetString("ProgrammableBlockExtensions_OnBindScriptDll_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing out extensions.
        /// </summary>
        internal static string ProgrammableBlockExtensions_Unload_Unloading {
            get {
                return ResourceManager.GetString("ProgrammableBlockExtensions_Unload_Unloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} does not have the required field {1}.
        /// </summary>
        internal static string Reflections_GetFieldInfo_MissingField {
            get {
                return ResourceManager.GetString("Reflections_GetFieldInfo_MissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} does not have the required method {1}({2}).
        /// </summary>
        internal static string Reflections_GetMethodInfo_MissingMethod {
            get {
                return ResourceManager.GetString("Reflections_GetMethodInfo_MissingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} does not have the required property {1}.
        /// </summary>
        internal static string Reflections_GetPropertyInfo_MissingProperty {
            get {
                return ResourceManager.GetString("Reflections_GetPropertyInfo_MissingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} does not exist.
        /// </summary>
        internal static string Reflections_Reflections_MissingType {
            get {
                return ResourceManager.GetString("Reflections_Reflections_MissingType", resourceCulture);
            }
        }
    }
}
